# Generated by Django 3.1.3 on 2021-01-25 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awward_app', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='profile_pic',
        ),
    ]
