# Generated by Django 3.1.3 on 2021-01-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awward_app', '0003_auto_20210125_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='profile',
        ),
    ]
