# Generated by Django 3.1.3 on 2021-01-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awward_app', '0005_auto_20210125_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='profile/'),
        ),
    ]
